SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE TABLE USER (
    AADHAR_NO INT(12) PRIMARY KEY,
    USERNAME VARCHAR(25) NOT NULL
);

CREATE TABLE DOC (
    DOC_ID INT(11) PRIMARY KEY,
    DOC_NAME VARCHAR(50) NOT NULL,
    PASSWORDS VARCHAR(20) NOT NULL
);

CREATE TABLE P_DETAILS (
    AADHAR_NO INT(12) REFERENCES USER(AADHAR_NO) ON DELETE CASCADE,
    AGE INT NOT NULL,
    BLOOD_GRP VARCHAR(5) NOT NULL,
    DOB DATE NOT NULL,
    CONTACT_NO INT(10) NOT NULL,
    ECONTACT_NO INT(10) NOT NULL,
    GENDER VARCHAR(1) NOT NULL
);

CREATE TABLE DIAGNOSE (
    AADHAR_NO INT(12) REFERENCES USER(AADHAR_NO) ON DELETE CASCADE,
    T_DATE DATE NOT NULL,
    APPEAREANCE VARCHAR(20) NOT NULL,
    BP VARCHAR(10) NOT NULL,
    MASS FLOAT(5) NOT NULL,
    TEMP INT NOT NULL,
    PULSE VARCHAR(10) NOT NULL, 
    REMARKS VARCHAR(100) NOT NULL,
    MEDICATION VARCHAR(100) NOT NULL
);

CREATE TABLE MED_HISTORY (
    AADHAR_NO INT(12) REFERENCES USER(AADHAR_NO) ON DELETE CASCADE,
    S_DATE DATE NOT NULL,
    E_DATE DATE DEFAULT NULL,
    SYMPTOMS VARCHAR(100) NOT NULL,
    DISEASE VARCHAR(25) NOT NULL,
    MEDICATION VARCHAR(100) REFERENCES DIAGNOSE(MEDICATION) ON DELETE CASCADE,
    DOC_NAME VARCHAR(25) NOT NULL,
    STAT VARCHAR(10) NOT NULL
);

CREATE TABLE OTHER_MED (
    AADHAR_NO INT(12) REFERENCES USER(AADHAR_NO) ON DELETE CASCADE,
    MEDS VARCHAR(100),
    ALLERGIES VARCHAR(50),
    INJURY VARCHAR(50) 
);

